from __future__ import annotations

from copy import deepcopy
from typing import Any

from core.status import RuntimeStatus

HTTP_SCHEMA_NAME = "meetyou.http.v1"
WS_SCHEMA_NAME = "meetyou.ws.v1"

WS_FRAME_KINDS = (
    "connection",
    "event",
    "runtime",
    "ack",
    "error",
    "health",
    "pong",
)

WS_EVENT_TYPES = (
    "message",
    "reasoning",
    "status",
    "control",
    "confirm_request",
    "human_input_request",
    "runtime_status",
    "usage",
    "error",
)

WS_RUNTIME_RESOURCES = ("state", "usage", "debug")

SUPPORTED_PROVIDER_OPTIONS = (
    {"label": "OpenAI", "value": "openai"},
    {"label": "Anthropic", "value": "anthropic"},
    {"label": "Gemini", "value": "gemini"},
    {"label": "Ollama", "value": "ollama"},
)

SUPPORTED_PROVIDER_VALUES = tuple(option["value"] for option in SUPPORTED_PROVIDER_OPTIONS)

WEB_SEARCH_QUALITY_OPTIONS = (
    {"label": "自适应", "value": "adaptive"},
    {"label": "快速", "value": "fast"},
    {"label": "均衡", "value": "balanced"},
    {"label": "深入", "value": "deep"},
)

THINKING_EFFORT_OPTIONS = (
    {"label": "低", "value": "low"},
    {"label": "中", "value": "medium"},
    {"label": "高", "value": "high"},
)

THINKING_EFFORT_VALUES = tuple(option["value"] for option in THINKING_EFFORT_OPTIONS)

CONFIG_GROUPS = (
    {
        "key": "model",
        "title": "模型",
        "description": "主模型提供商、模型名称与默认推理设置。",
    },
    {
        "key": "secrets",
        "title": "密钥",
        "description": "API Key 与其他敏感集成凭证。",
    },
    {
        "key": "memory",
        "title": "记忆",
        "description": "Embedding、记忆持久化与相关配置。",
    },
    {
        "key": "heartbeat",
        "title": "心跳",
        "description": "后台心跳模型与运行频率控制。",
    },
    {
        "key": "modes",
        "title": "模式",
        "description": "助手模式路由、可信写入目录与 JSON 配置包。",
    },
    {
        "key": "advanced",
        "title": "高级",
        "description": "Gateway、飞书、MCP 等集成配置。",
    },
)

CONFIG_FIELD_SCHEMAS: dict[str, dict[str, Any]] = {
    "api_provider": {
        "title": "主模型提供商",
        "description": "主对话模型使用的服务提供商。",
        "group": "model",
        "input": "select",
        "options": list(SUPPORTED_PROVIDER_OPTIONS),
    },
    "api_url": {
        "title": "主模型 API 地址",
        "description": "主模型接口使用的基础 URL。",
        "group": "model",
        "input": "text",
        "placeholder": "https://api.openai.com/v1/responses",
        "help_text": "填写完整 HTTP(S) 地址，通常包含版本或接口路径；不要填写 API Key。",
        "examples": ["https://api.openai.com/v1/responses", "http://127.0.0.1:11434/v1/chat/completions"],
    },
    "model": {
        "title": "主模型名称",
        "description": "主对话流程使用的模型名称。",
        "group": "model",
        "input": "text",
        "placeholder": "gpt-5.4",
        "help_text": "填写服务商真实模型 ID。模型名变化较快，因此保留手动输入。",
        "examples": ["gpt-5.4", "claude-sonnet-4-5", "gemini-2.5-pro"],
    },
    "thinking_enabled": {
        "title": "默认启用推理",
        "description": "是否默认开启推理能力。",
        "group": "model",
        "input": "boolean",
    },
    "thinking_effort": {
        "title": "推理强度",
        "description": "模型支持时使用的默认推理强度。",
        "group": "model",
        "input": "select",
        "options": list(THINKING_EFFORT_OPTIONS),
    },
    "thinking_budget_tokens": {
        "title": "推理预算",
        "description": "可选的推理 Token 预算。",
        "group": "model",
        "input": "number",
    },
    "api_key": {
        "title": "主模型 API Key",
        "description": "主模型提供商使用的密钥。",
        "group": "secrets",
        "input": "password",
    },
    "heartbeat_api_key": {
        "title": "心跳模型 API Key",
        "description": "心跳模型提供商使用的密钥。",
        "group": "secrets",
        "input": "password",
        "advanced": True,
    },
    "embedding_api_key": {
        "title": "Embedding API Key",
        "description": "Embedding 服务使用的密钥。",
        "group": "secrets",
        "input": "password",
        "advanced": True,
    },
    "client_access_token": {
        "title": "端点提供方访问令牌",
        "description": "桌面端点与边缘端点连接核心服务 `/endpoint/ws` 时使用的令牌；正式主来源优先取环境变量。",
        "group": "secrets",
        "input": "password",
        "advanced": True,
    },
    "database_url": {
        "title": "数据库连接串",
        "description": "核心服务使用的 PostgreSQL 连接串。",
        "group": "secrets",
        "input": "password",
        "advanced": True,
    },
    "gateway_access_token": {
        "title": "网关访问令牌",
        "description": "HTTP 与 WebSocket 访问统一使用的受保护令牌。",
        "group": "secrets",
        "input": "password",
        "advanced": True,
    },
    "feishu_app_id": {
        "title": "飞书应用 ID",
        "description": "飞书应用的 App ID。",
        "group": "secrets",
        "input": "password",
        "advanced": True,
    },
    "feishu_app_secret": {
        "title": "飞书应用 Secret",
        "description": "飞书应用的密钥。",
        "group": "secrets",
        "input": "password",
        "advanced": True,
    },
    "notion_token": {
        "title": "Notion Token",
        "description": "Notion 集成或 MCP 使用的令牌。",
        "group": "secrets",
        "input": "password",
        "advanced": True,
    },
    "tavily_api_key": {
        "title": "Tavily API Key",
        "description": "网页研究能力使用的令牌。",
        "group": "secrets",
        "input": "password",
        "advanced": True,
    },
    "embedding_api_url": {
        "title": "Embedding API 地址",
        "description": "Embedding 服务的接口地址。",
        "group": "memory",
        "input": "text",
        "help_text": "填写 Embedding API 的完整 HTTP(S) 地址。",
        "examples": ["https://api.openai.com/v1/embeddings"],
    },
    "embedding_model": {
        "title": "Embedding 模型",
        "description": "Embedding 使用的模型名称。",
        "group": "memory",
        "input": "text",
    },
    "memory_file_path": {
        "title": "记忆文件路径",
        "description": "记忆图持久化文件的保存路径。",
        "group": "memory",
        "input": "text",
        "advanced": True,
        "help_text": "填写 JSON 状态文件路径；通常放在 user/ 下，避免提交到 Git。",
        "examples": ["user/memory_state.json"],
    },
    "task_file_path": {
        "title": "任务文件路径",
        "description": "任务与调度状态持久化文件的保存路径。",
        "group": "memory",
        "input": "text",
        "advanced": True,
        "placeholder": "user/memory_tasks.json",
        "help_text": "填写任务状态 JSON 文件路径；通常放在 user/ 下。",
        "examples": ["user/memory_tasks.json"],
    },
    "heartbeat_api_provider": {
        "title": "心跳模型提供商",
        "description": "心跳模型使用的服务提供商。",
        "group": "heartbeat",
        "input": "select",
        "options": list(SUPPORTED_PROVIDER_OPTIONS),
        "advanced": True,
    },
    "heartbeat_api_url": {
        "title": "心跳模型 API 地址",
        "description": "心跳模型接口使用的基础 URL。",
        "group": "heartbeat",
        "input": "text",
        "advanced": True,
        "help_text": "留空时通常复用主模型地址；填写时使用完整 HTTP(S) 地址。",
        "examples": ["https://api.openai.com/v1/responses"],
    },
    "heart_model": {
        "title": "心跳模型名称",
        "description": "心跳流程使用的模型名称。",
        "group": "heartbeat",
        "input": "text",
    },
    "heartbeat_interval": {
        "title": "心跳间隔",
        "description": "心跳循环的执行间隔，单位为秒。",
        "group": "heartbeat",
        "input": "number",
    },
    "heartbeat_idle_poke_enabled": {
        "title": "空闲主动触达",
        "description": "用户空闲超过阈值后是否允许助手主动发起一句轻量触达。",
        "group": "heartbeat",
        "input": "boolean",
    },
    "heartbeat_idle_poke_after_seconds": {
        "title": "空闲触达阈值",
        "description": "用户最近活动后经过多少秒可触发空闲主动触达，默认 3600。",
        "group": "heartbeat",
        "input": "number",
    },
    "heartbeat_idle_poke_cooldown_seconds": {
        "title": "空闲触达冷却",
        "description": "两次空闲主动触达之间的最小间隔，默认 3600 秒。",
        "group": "heartbeat",
        "input": "number",
    },
    "heartbeat_idle_context_compaction_enabled": {
        "title": "空闲触达前压缩上下文",
        "description": "首次空闲主动触达前是否将长会话压缩为持久摘要，并让后续正常对话复用该摘要。",
        "group": "heartbeat",
        "input": "boolean",
        "advanced": True,
    },
    "housekeeping_interval": {
        "title": "清理间隔",
        "description": "记忆清理循环的执行间隔，单位为秒。",
        "group": "heartbeat",
        "input": "number",
        "advanced": True,
    },
    "scheduler_interval": {
        "title": "调度轮询间隔",
        "description": "定时任务轮询间隔，单位为秒。",
        "group": "heartbeat",
        "input": "number",
        "advanced": True,
    },
    "heartbeat_path": {
        "title": "心跳提示词路径",
        "description": "心跳循环使用的提示词文件路径。",
        "group": "heartbeat",
        "input": "text",
        "advanced": True,
        "help_text": "填写本地提示词文件路径；相对路径会按项目根目录解析。",
        "examples": ["prompt/heart.md"],
    },
    "assistant_modes": {
        "title": "助手模式配置",
        "description": "定义模式、共享基础工具、提示词注册、技能注册与工具包的 JSON 配置。",
        "group": "modes",
        "input": "json",
        "help_text": "必须是 JSON 对象。仅在需要调整模式、SKILL 注册或工具包时修改。",
        "examples": ["{\"default_mode\":\"general\"}"],
    },
    "mode_router": {
        "title": "模式路由配置",
        "description": "用于 Brain 决策、会话内切换与启发式回退策略的 JSON 配置。",
        "group": "modes",
        "input": "json",
        "help_text": "必须是 JSON 对象。普通模式选择不需要改这里。",
        "examples": ["{\"default_mode\":\"general\"}"],
    },
    "trusted_write_roots": {
        "title": "可信写入目录",
        "description": "无需额外放宽信任边界即可写入本地文档的目录列表。",
        "group": "modes",
        "input": "list",
        "control": "directory_list",
        "help_text": "每项是一个允许写入的目录；建议使用本机绝对路径，少量精确授权。",
        "examples": ["E:\\Documents\\MeetYou", "D:\\Work\\Reports"],
    },
    "source_catalog_path": {
        "title": "信息源目录路径",
        "description": "配置驱动的信息源目录 JSON 文件路径。",
        "group": "modes",
        "input": "text",
        "placeholder": "user/source_catalog.json",
        "help_text": "填写来源目录 JSON 文件路径；相对路径会按项目根目录解析。",
        "examples": ["user/source_catalog.json"],
    },
    "document_parsers": {
        "title": "文档解析配置",
        "description": "本地文档解析限制与 OCR 能力的 JSON 配置。",
        "group": "modes",
        "input": "json",
        "help_text": "必须是 JSON 对象。用于限制文档大小、页数、OCR 等解析行为。",
    },
    "office_integrations": {
        "title": "Office 集成配置",
        "description": "Office 集成能力与仅草稿行为的 JSON 配置。",
        "group": "modes",
        "input": "json",
        "help_text": "必须是 JSON 对象。用于配置 Word/Excel/PowerPoint 草稿和集成策略。",
    },
    "research_contact_email": {
        "title": "研究联系邮箱",
        "description": "部分官方 API 要求提供时使用的联系邮箱或 User-Agent 提示。",
        "group": "advanced",
        "input": "text",
        "advanced": True,
        "placeholder": "research@example.com",
    },
    "enable_feishu_bot": {
        "title": "启用飞书端点提供方",
        "description": "启用飞书外部端点提供方，通过 Thread / Run / Delivery 主链接入核心服务。",
        "group": "advanced",
        "input": "boolean",
        "advanced": True,
    },
    "enable_meetwechat_client": {
        "title": "启用 MeetWeChat 端点提供方",
        "description": "启用 MeetWeChat 本地服务代理真实微信账号，并通过正式端点 API 与 /endpoint/ws 接入核心服务。",
        "group": "advanced",
        "input": "boolean",
        "advanced": True,
    },
    "meetwechat_base_url": {
        "title": "MeetWeChat API 地址",
        "description": "MeetWeChat /v1 HTTP API 基础地址，默认 http://127.0.0.1:38961。",
        "group": "advanced",
        "input": "text",
        "advanced": True,
        "placeholder": "http://127.0.0.1:38961",
        "help_text": "填写 MeetWeChat 本地 HTTP API 基础地址。",
        "examples": ["http://127.0.0.1:38961"],
    },
    "meetwechat_poll_interval_seconds": {
        "title": "MeetWeChat 轮询间隔",
        "description": "没有入站推送时轮询 /v1/events 的空闲间隔，单位秒；默认 2。",
        "group": "advanced",
        "input": "number",
        "advanced": True,
    },
    "meetwechat_error_backoff_seconds": {
        "title": "MeetWeChat 错误退避",
        "description": "MeetWeChat 轮询失败后的初始退避秒数，指数增加但最高 30 秒；默认 2。",
        "group": "advanced",
        "input": "number",
        "advanced": True,
    },
    "meetwechat_max_text_chars": {
        "title": "MeetWeChat 文本分段长度",
        "description": "通过 /v1/messages/text 发送长文本时的单段最大字符数，默认 1800。",
        "group": "advanced",
        "input": "number",
        "advanced": True,
    },
    "meetwechat_state_file": {
        "title": "MeetWeChat 状态文件",
        "description": "保存事件去重、ACK 待补偿、会话线程与群成员别名状态；不要提交到 Git。",
        "group": "advanced",
        "input": "text",
        "advanced": True,
        "placeholder": "user/meetwechat_client_state.json",
        "help_text": "填写本地状态 JSON 文件路径；不要放到会提交 Git 的位置。",
        "examples": ["user/meetwechat_client_state.json"],
    },
    "meetwechat_proxy_policy": {
        "title": "MeetWeChat 代理策略",
        "description": "JSON 对象。默认 guarded_auto：私聊自动代理，群聊仅 @ 助理或显式规则时回复。",
        "group": "advanced",
        "input": "json",
        "advanced": True,
        "help_text": "必须是 JSON 对象。常用策略是 guarded_auto。",
        "examples": ["{\"mode\":\"guarded_auto\"}"],
    },
    "max_parallel_tool_calls": {
        "title": "最大并行工具调用数",
        "description": "安全只读工具的小并发上限。默认 3。",
        "group": "advanced",
        "input": "number",
        "advanced": True,
    },
    "web_search_quality": {
        "title": "网页搜索质量",
        "description": "可选 adaptive、fast、balanced 或 deep。默认 adaptive。",
        "group": "advanced",
        "input": "select",
        "options": list(WEB_SEARCH_QUALITY_OPTIONS),
        "advanced": True,
        "placeholder": "adaptive",
    },
    "web_search_parallel_reads": {
        "title": "网页搜索并行读取数",
        "description": "search_web 抽取来源时的并发上限。默认 3。",
        "group": "advanced",
        "input": "number",
        "advanced": True,
    },
    "web_search_extract_timeout_seconds": {
        "title": "网页内容抽取超时",
        "description": "网页搜索中 Tavily 抽取调用的超时时间。默认 6 秒。",
        "group": "advanced",
        "input": "number",
        "advanced": True,
    },
    "memory_auto_search_timeout_ms": {
        "title": "自动记忆搜索超时",
        "description": "自动记忆预取的最长等待时间。默认 1200 毫秒。",
        "group": "advanced",
        "input": "number",
        "advanced": True,
    },
    "memory_background_episode_save": {
        "title": "后台保存记忆片段",
        "description": "在回答关键路径之外保存自动生成的用户回合片段。",
        "group": "advanced",
        "input": "boolean",
        "advanced": True,
    },
    "meetwechat_inbound_worker_count": {
        "title": "MeetWeChat 入站工作线程数",
        "description": "并发处理入站事件的工作线程数；同一会话仍保持顺序。默认 4。",
        "group": "advanced",
        "input": "number",
        "advanced": True,
    },
    "meetwechat_inbound_queue_size": {
        "title": "MeetWeChat 入站队列大小",
        "description": "/v1/events 批次的背压队列大小。默认 500。",
        "group": "advanced",
        "input": "number",
        "advanced": True,
    },
    "meetwechat_outbound_worker_count": {
        "title": "MeetWeChat 出站工作线程数",
        "description": "并发发送出站消息的工作线程数。默认 2。",
        "group": "advanced",
        "input": "number",
        "advanced": True,
    },
    "meetwechat_outbound_queue_size": {
        "title": "MeetWeChat 出站队列大小",
        "description": "/v1/messages/text 发送任务的队列大小。默认 500。",
        "group": "advanced",
        "input": "number",
        "advanced": True,
    },
    "meetwechat_outbound_min_interval_ms": {
        "title": "MeetWeChat 发送间隔",
        "description": "两次 /v1/messages/text 调用之间的最小间隔。默认 250 毫秒。",
        "group": "advanced",
        "input": "number",
        "advanced": True,
    },
    "meetwechat_send_timeout_ms": {
        "title": "MeetWeChat 发送超时",
        "description": "单次 /v1/messages/text 调用的超时时间。默认 10000 毫秒。",
        "group": "advanced",
        "input": "number",
        "advanced": True,
    },
    "meetwechat_state_flush_interval_ms": {
        "title": "MeetWeChat 状态写入间隔",
        "description": "事件、ACK、线程和别名状态写入的防抖窗口。默认 500 毫秒。",
        "group": "advanced",
        "input": "number",
        "advanced": True,
    },
    "meetwechat_gateway_endpoint_idle_ttl_seconds": {
        "title": "MeetWeChat 端点会话空闲保留时间",
        "description": "超过该秒数未使用后关闭缓存的网关端点会话。默认 600。",
        "group": "advanced",
        "input": "number",
        "advanced": True,
    },
    "gateway_host": {
        "title": "网关主机地址",
        "description": "网关使用的主机地址。",
        "group": "advanced",
        "input": "text",
        "advanced": True,
        "help_text": "本地开发通常使用 127.0.0.1；暴露到外部网络时必须配置访问令牌。",
        "examples": ["127.0.0.1", "0.0.0.0"],
    },
    "core_base_url": {
        "title": "Core 服务地址",
        "description": "Endpoint Provider 连接 Core 的 HTTP 基础地址；未设置时回退 gateway_host/gateway_port。",
        "group": "advanced",
        "input": "text",
        "advanced": True,
        "help_text": "填写 Core 服务 HTTP 基础地址，不要包含 /runtime 路径。",
        "examples": ["http://127.0.0.1:8000", "https://core.example.com"],
    },
    "gateway_port": {
        "title": "网关端口",
        "description": "网关使用的端口号。",
        "group": "advanced",
        "input": "number",
        "advanced": True,
    },
    "gateway_cors_origins": {
        "title": "网关允许来源",
        "description": "允许访问网关的额外浏览器来源列表。",
        "group": "advanced",
        "input": "list",
        "advanced": True,
        "help_text": "每行一个浏览器 Origin，格式为 scheme://host[:port]。",
        "examples": ["http://127.0.0.1:5173", "https://app.example.com"],
    },
    "feishu_broadcast_chat_ids": {
        "title": "飞书广播会话 ID",
        "description": "每行填写一个会话 ID。",
        "group": "advanced",
        "input": "list",
        "advanced": True,
        "help_text": "每行一个飞书 chat_id；需要从飞书端点发现或平台配置中获取。",
    },
    "feishu_default_chat_id": {
        "title": "默认飞书会话 ID",
        "description": "默认发送消息的飞书会话目标。",
        "group": "advanced",
        "input": "text",
        "advanced": True,
        "help_text": "填写飞书 chat_id。该值来自飞书平台或已发现会话，不适合固定下拉。",
    },
    "feishu_chat_registry_path": {
        "title": "飞书会话注册表路径",
        "description": "用于保存已发现会话 ID 的文件路径。",
        "group": "advanced",
        "input": "text",
        "advanced": True,
        "help_text": "填写本地 JSON 文件路径，通常放在 user/ 下。",
        "examples": ["user/feishu_chats.json"],
    },
    "cmd_policy_path": {
        "title": "命令策略路径",
        "description": "命令安全策略文件路径。",
        "group": "advanced",
        "input": "text",
        "advanced": True,
        "help_text": "填写命令策略 JSON 文件路径；桌面端本地执行会读取该文件。",
        "examples": ["user/cmd_policy.json"],
    },
    "tools_schema_path": {
        "title": "工具 Schema 路径",
        "description": "工具 Schema 文件路径。",
        "group": "advanced",
        "input": "text",
        "advanced": True,
        "help_text": "填写工具定义 JSON 文件路径。",
        "examples": ["user/tools.json"],
    },
    "soul_path": {
        "title": "Soul 提示词路径",
        "description": "主系统提示词文件路径。",
        "group": "advanced",
        "input": "text",
        "advanced": True,
        "help_text": "填写本地提示词文件路径；相对路径会按项目根目录解析。",
        "examples": ["prompt/soul.md"],
    },
    "start_path": {
        "title": "Start 提示词路径",
        "description": "启动提示词文件路径。",
        "group": "advanced",
        "input": "text",
        "advanced": True,
        "help_text": "填写本地提示词文件路径；相对路径会按项目根目录解析。",
        "examples": ["prompt/start.md"],
    },
    "mcp_registry_url": {
        "title": "MCP 注册表地址",
        "description": "MCP 注册表的访问地址。",
        "group": "advanced",
        "input": "text",
        "advanced": True,
        "help_text": "填写 MCP registry HTTP(S) 地址。",
        "examples": ["https://registry.example.com/mcp"],
    },
}

CONFIG_FIELD_KEYS = tuple(CONFIG_FIELD_SCHEMAS.keys())
RUNTIME_STATUS_VALUES = tuple(status.value for status in RuntimeStatus)


def build_ui_protocol_schema() -> dict[str, Any]:
    return {
        "http_schema": HTTP_SCHEMA_NAME,
        "ws_schema": WS_SCHEMA_NAME,
        "ws_frame_kinds": list(WS_FRAME_KINDS),
        "ws_event_types": list(WS_EVENT_TYPES),
        "ws_runtime_resources": list(WS_RUNTIME_RESOURCES),
        "runtime_statuses": list(RUNTIME_STATUS_VALUES),
        "providers": deepcopy(list(SUPPORTED_PROVIDER_OPTIONS)),
        "thinking_efforts": deepcopy(list(THINKING_EFFORT_OPTIONS)),
        "config_groups": deepcopy(list(CONFIG_GROUPS)),
        "config_fields": [
            {"key": key, **deepcopy(value)}
            for key, value in CONFIG_FIELD_SCHEMAS.items()
        ],
    }
