from __future__ import annotations

import argparse
import secrets
import shutil
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
USER_TEMPLATE_FILES = (
    ("config.example.json", "config.json"),
    ("tools.example.json", "tools.json"),
    ("cmd_policy.example.json", "cmd_policy.json"),
    ("source_catalog.example.json", "source_catalog.json"),
    ("memory_graph.example.json", "memory_graph.json"),
)


def _copy_if_missing(source: Path, target: Path, *, force: bool = False) -> bool:
    if target.exists() and not force:
        return False
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, target)
    return True


def _write_if_missing(path: Path, content: str, *, force: bool = False) -> bool:
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def _merge_env_if_missing(path: Path, defaults: dict[str, str], *, force: bool = False) -> list[str]:
    if force or not path.exists():
        _write_if_missing(path, "\n".join(f"{key}={value}" for key, value in defaults.items()) + "\n", force=True)
        return sorted(defaults)
    lines = path.read_text(encoding="utf-8").splitlines()
    existing: dict[str, str] = {}
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        existing[key.strip()] = value.strip()
    added = []
    rendered = []
    replaced = []
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            rendered.append(line)
            continue
        key, value = stripped.split("=", 1)
        key = key.strip()
        if key in defaults and "replace_with" in value:
            rendered.append(f"{key}={defaults[key]}")
            replaced.append(key)
        else:
            rendered.append(line)
    for key, value in defaults.items():
        if key in existing:
            continue
        rendered.append(f"{key}={value}")
        added.append(key)
    if added or replaced:
        path.write_text("\n".join(rendered).rstrip() + "\n", encoding="utf-8")
    return sorted(set(added) | set(replaced))


def _read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def _secret(length: int = 32) -> str:
    return secrets.token_urlsafe(length)


def _compose_env() -> str:
    return "\n".join(f"{key}={value}" for key, value in _compose_env_defaults().items()) + "\n"


def _compose_env_defaults() -> dict[str, str]:
    postgres_password = _secret(24)
    gateway_token = _secret(32)
    return {
        "TZ": "Asia/Shanghai",
        "POSTGRES_DB": "meetyou",
        "POSTGRES_USER": "meetyou",
        "POSTGRES_PASSWORD": postgres_password,
        "POSTGRES_HOST_PORT": "55432",
        "MEETYOU_DATABASE_URL": f"postgresql+psycopg://meetyou:{postgres_password}@postgres:5432/meetyou",
        "MEETYOU_GATEWAY_ACCESS_TOKEN": gateway_token,
        "MEETYOU_GATEWAY_HOST_PORT": "8000",
    }


def _compose_env_with_comments() -> str:
    values = _compose_env_defaults()
    return "\n".join(
        [
            "# Docker-local overrides for deploy/docker/compose.core-postgres.yml",
            "# Generated by scripts/prepare_core_runtime.py.",
            "",
            *(f"{key}={value}" for key, value in values.items()),
            "",
        ]
    )


def _runtime_core_env() -> str:
    return "\n".join(
        [
            "# Runtime secrets for the Core service.",
            "# Fill deployment-specific values here when they should override compose.env.",
            "",
        ]
    )


def prepare_host(*, force: bool = False) -> list[str]:
    changed: list[str] = []
    if _copy_if_missing(REPO_ROOT / ".env.example", REPO_ROOT / ".env", force=force):
        changed.append(".env")
    for source_name, target_name in USER_TEMPLATE_FILES:
        if _copy_if_missing(REPO_ROOT / "user" / source_name, REPO_ROOT / "user" / target_name, force=force):
            changed.append(f"user/{target_name}")
    return changed


def prepare_docker(output_root: Path, *, force: bool = False) -> list[str]:
    changed: list[str] = []
    if _copy_if_missing(REPO_ROOT / ".env.example", REPO_ROOT / ".env", force=force):
        changed.append(".env")
    compose_env = REPO_ROOT / "deploy" / "docker" / "compose.env"
    if not compose_env.exists() or force:
        if _write_if_missing(compose_env, _compose_env_with_comments(), force=force):
            changed.append(str(compose_env.relative_to(REPO_ROOT)))
    else:
        added_keys = _merge_env_if_missing(compose_env, _compose_env_defaults())
        if added_keys:
            changed.append(f"{compose_env.relative_to(REPO_ROOT)} ({', '.join(added_keys)})")
    core_env = output_root / "core.env"
    if _write_if_missing(core_env, _runtime_core_env(), force=force):
        changed.append(str(core_env.relative_to(REPO_ROOT)))
    else:
        compose_values = _read_env(compose_env)
        propagated_keys = {
            key: compose_values[key]
            for key in (
                "MEETYOU_DATABASE_URL",
                "MEETYOU_GATEWAY_ACCESS_TOKEN",
            )
            if key in compose_values and compose_values[key]
        }
        replaced_keys = _merge_env_if_missing(core_env, propagated_keys)
        if replaced_keys:
            changed.append(f"{core_env.relative_to(REPO_ROOT)} ({', '.join(replaced_keys)})")

    for directory in ("logs", "user"):
        path = output_root / directory
        path.mkdir(parents=True, exist_ok=True)

    docker_templates = (("config.docker.example.json", "config.json"),) + USER_TEMPLATE_FILES[1:]
    for source_name, target_name in docker_templates:
        if _copy_if_missing(REPO_ROOT / "user" / source_name, output_root / "user" / target_name, force=force):
            changed.append(str((output_root / "user" / target_name).relative_to(REPO_ROOT)))
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description="Prepare MeetYou Core runtime files.")
    parser.add_argument("--profile", choices=("host", "docker"), default="host")
    parser.add_argument("--output-root", default="deploy/docker/runtime")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    if args.profile == "host":
        changed = prepare_host(force=args.force)
    else:
        changed = prepare_docker(REPO_ROOT / args.output_root, force=args.force)

    if changed:
        print("prepared:")
        for item in changed:
            print(f"- {item}")
    else:
        print("runtime files already present")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
